trigger:
  - main

pr: none

schedules:
  - cron: "0 0 * * 0"
    displayName: Scheduled build once per week
    branches:
      include:
        - main

resources:
  - repo: self

variables:
  repository: 'godeltech/owasp-dependency-checker'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
      - task: Docker@2
        displayName: Build and Push an image
        inputs:
          containerRegistry: 'docker-hub'
          repository: $(repository)
          command: 'buildAndPush'
          Dockerfile: './src/Dockerfile'
          tags: |
            latest
