trigger:
  - main

pr: none

resources:
  - repo: self

variables:
  repository: 'godeltech/owasp-dependency-checker'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
          - task: gitversion/setup@0
            displayName: Setup GitVersion
            inputs:
             versionSpec: '5.x'
          - task: gitversion/execute@0
            displayName: Execute GitVersion
          - task: Docker@2
            displayName: Build and Push an image
            inputs:
              containerRegistry: 'docker-hub'
              repository: $(repository)
              command: 'buildAndPush'
              Dockerfile: './src/Dockerfile'
              tags: |
                $(Build.BuildNumber)
                latest
